# Generated by Django 6.0.7 on 2026-07-13 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500)),
                ('url', models.URLField(max_length=500)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='reader.post')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
