# Generated by Django 6.0.7 on 2026-07-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_youtubevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, help_text='Exibe o post na seção Destaques do dashboard.'),
        ),
    ]
