"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis do arquivo .env (se existir) para o ambiente
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-gk*-^=ph%bw#6w*r04gf_7_j)$cgsq8frs8ymj(5&z(jep#9_r',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Origens confiáveis para CSRF (ex.: https://meudominio.com). Vazio por padrão.
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o
]

# USE_X_FORWARDED_HOST = True
# SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# SECURE_SSL_REDIRECT = False

# SESSION_COOKIE_SECURE = False
# CSRF_COOKIE_SECURE = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auth_app',
    'reader',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Authentication
LOGIN_URL = 'auth_app:login'
LOGIN_REDIRECT_URL = 'reader:dashboard'
LOGOUT_REDIRECT_URL = 'auth_app:login'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_DATABASE_URL = os.environ.get('DATABASE_URL', '')

if _DATABASE_URL.startswith('libsql://'):
    # Turso / libSQL (cliente HTTP puro-Python via django-libsql).
    # O token pode vir na própria URL (?authToken=...) ou em TURSO_AUTH_TOKEN.
    _name = _DATABASE_URL
    _token = os.environ.get('TURSO_AUTH_TOKEN', '')
    if _token and 'authToken=' not in _name:
        _sep = '&' if '?' in _name else '?'
        _name = f"{_name}{_sep}authToken={_token}"
    DATABASES = {
        'default': {
            'ENGINE': 'libsql.db.backends.sqlite3',
            'NAME': _name,
        }
    }
else:
    # DATABASE_URL faz o parse via dj-database-url; padrão: SQLite local.
    _db = dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=int(os.environ.get('CONN_MAX_AGE', 600)),
    )

    # Compatibilidade com pgBouncer em modo "transaction" (ex.: pooler do Supabase na
    # porta 6543): esse modo não suporta prepared statements nem conexões persistentes.
    _is_transaction_pooler = str(_db.get('PORT')) == '6543' or env_bool('DB_TRANSACTION_POOLER', False)
    if _db.get('ENGINE', '').endswith('postgresql') and _is_transaction_pooler:
        _db['CONN_MAX_AGE'] = 0
        _db['DISABLE_SERVER_SIDE_CURSORS'] = True
        _db.setdefault('OPTIONS', {})['prepare_threshold'] = None

    DATABASES = {'default': _db}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Boa_Vista'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Destino do `collectstatic` (usado em produção/Docker)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise serve os estáticos comprimidos direto pelo app (sem nginx)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}